### ISSUE TITLE
Error when going to production

### ISSUE THREAD

**Issue by jeverduzco** [nuxt-community/vuetify-module#67]
When I'm in dev mode my page looks perfect (see image 1) 

Image 1 : https://imgur.com/ssETPG9

but when running npm run build and npm start it looks totally different (see image 2)

Image 2: https://imgur.com/Xu8GzBd

As can be seen in the images in development mode if the content is centered and when going to production looks bad.

Any idea?

This happened when I updated yesterday to the new version.

**Comment by jeverduzco** [comment]
I think it's a bug in version 2.0 that doesn't compile .container so I guess it's a wait and see update.

**Comment by kevinmarrec** [comment]
Can't help without repository, if you found an issue related on Vuetify repo please copy link here thanks

**Comment by jeverduzco** [comment]
@kevinmarrec Here is already open the issue in the repo of Vuetify: https://github.com/vuetifyjs/vuetify/issues/7978

**Comment by kevinmarrec** [comment]
@jeverduzco It's reproducible without Nuxt i.e. with Vue CLI ?

**Comment by Mnwa** [comment]
Have are some problem

**Comment by jeverduzco** [comment]
@kevinmarrec I have only reproduced it in Nuxt but from what I see in the discord chat is happening to many by running npm run build and npm start.

**Comment by franzyke** [comment]
I'm getting this error without nuxt

**Comment by Mnwa** [comment]
I think is problem in the vuetify loader, because if I set property treeShake to false then all right

**Comment by jeverduzco** [comment]
@Mnwa @kevinmarrec Confirmed if I set treeShake to false works.

**Comment by kevinmarrec** [comment]
@jeverduzco Yeah, in dev mode `treeShake` is false by default, that's why you don't have the issue in development but in production. Let's wait for Vuetify team answers around https://github.com/vuetifyjs/vuetify/issues/7978 , I pinged them on Discord.

**Comment by kevinmarrec** [comment]
@jeverduzco It should have been fixed in Vuetify [**2.0.1**](https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.1)
I've updated dependencies and published @nuxtjs/vuetify@**1.0.1**

Can you try upgrading and tell me if it fixed your issue ?
If it does please close this issue :)

**Comment by Mnwa** [comment]
Hey! Now it don't build vuetify components in treeShake mode + production.
<img width="549" alt="Снимок экрана 2019-07-26 в 2 53 53" src="https://user-images.githubusercontent.com/8988331/61916317-b9be1f00-af50-11e9-881c-2080655b6fca.png">

**Comment by kevinmarrec** [comment]
@Mnwa I tested `build` + `start` locally and then in production environment the last version of the Vuetify module, and I didn't experience the issue about Vuetify components not built.

**Comment by jeverduzco** [comment]
Hi @kevinmarrec I updated and changed treeShake to true and effectively the bug is fixed, thank you.

**Comment by gotenxds** [comment]
I still get this after updating to 2.0.3, it works fine with treeShake off, anything else I might be missing ?

**Comment by kevinmarrec** [comment]
@gotenxds Could you provide the repository (or create a new one) with the issue you take the screenshots here ? I'll investigate from that thanks

**Comment by jeverduzco** [comment]
Upgrade to the latest version of the module and I have no problems: https://imgur.com/tkPAOjN

**Comment by gotenxds** [comment]
@kevinmarrec 
https://github.com/gotenxds/notamimic/
Thanks for the help !

**Comment by jeverduzco** [comment]
Hi @gotenxds I already reviewed your project and you must move the vuetify module from the production to the development dependencies as shown in image 1.

Image 1: https://imgur.com/kQ8j0ik

With that it works as you can see in image 2: https://imgur.com/d1gtFIv

**Comment by kevinmarrec** [comment]
@gotenxds I cloned your project, `yarn install` + `yarn build` + `yarn start` and didn't see issues, while treeShaking is set to `false`. Am i missing something ?

**Comment by gotenxds** [comment]
@kevinmarrec 
The issue is when treeShaking is set to true

**Comment by kevinmarrec** [comment]
@gotenxds It seems to be because you're using Nuxt programtaically but I've no clues about what's going on for now :/. It's way too hard to debug, maybe having a repository with the same bug reproduction but with a little app context would help me to find the issue.

**Comment by gotenxds** [comment]
@kevinmarrec 
Thanks for trying to help, what do you mean by using nuxt problematically ? 
Am I doing something weird or uncommon here? I'm coming from a react (2y) and angular (4y) background and been using vue for just 2 weeks so if I'm doing something off I'd like to know.

Anyway I'l try to repo it on a smaller scale, but not knowing what caused it will make it difficult :\
Thanks again.

**Comment by kevinmarrec** [comment]
@gotenxds Programatically (https://nuxtjs.org/api/nuxt#using-nuxt-js-programmatically), it means you use external server to build nuxt instead of just Nuxt. But it should be fine, it's just that it seems somehow `vuetify-loader` doesn't do anything, it should import the Vuetify components but I don't think it does and that's why the production version of your app is broken.

Smaller scale should just about having a `server/index.js` (it doesn't need to be typescript to reproduce issue) that build Nuxt, and just have the vuetify module installed.

**Comment by Mnwa** [comment]
Hey! It's vuetify loader bug I think. I create issue for it https://github.com/vuetifyjs/vuetify-loader/issues/71

**Comment by morficus** [comment]
Hello!
I am also running in to the same issue where when `treeShake` is true some things get screwy. 
Not sure if this module does anything particular during tree shaking or if it is just a proxy to the vuetify-loader... but I'm in the process of creating a repo to recreate the issue, so I'll be creating a new issue in a bit.
