### ISSUE TITLE
Some styles are missing after using tree-shaking

### ISSUE THREAD

**Issue by jhd4tmr** [nuxt-community/vuetify-module#73]
Like v-simple-table row:hover style is missing after setting process.env.NODE_ENV === 'production' using treeShake.

**Comment by kevinmarrec** [comment]
@jhd4tmr @velidonmez @stoneslasley

Anyone can give me more context ? What is `row:hover` ?
Can you please provide a repository with reproduction (or a CodeSandBox / or at least a Vuetify snippet) ?

**Comment by ricardogobbosouza** [comment]
@kevinmarrec 
I think with this last update it was solved

**Comment by kevinmarrec** [comment]
@ricardogobbosouza Maybe but I'm not sure if it's related to `container` styling issue

**Comment by kevinmarrec** [comment]
Still reproducible, it seems `VSimpleTable` relies on `VDataTable` styles which are not correctly imported by `vuetfiy-loader`

![Screenshot from 2019-07-29 15-41-21](https://user-images.githubusercontent.com/25272043/62053192-67faea80-b217-11e9-8053-7218c2f4d959.png)

**Comment by kevinmarrec** [comment]
@jhd4tmr Current workaround until it's fixed around Vuetify :

Add
```
@import 'vuetify/src/components/VDataTable/VDataTable.sass'
```

in the `style` section of all pages/components you're using `VSimpleTable` component.

**Comment by kevinmarrec** [comment]
Fixed on last release (1.1.1) through Vuetify 2.0.4 upgrade
https://github.com/vuetifyjs/vuetify/pull/8165
https://github.com/nuxt-community/vuetify-module/commit/a6e99fd4f62f29ad1b03bd99345aa21e0a466daf
https://github.com/nuxt-community/vuetify-module/commit/63554d74d57dcd7cd76f8f6eb9e3575bc42f06a1
